main:
  gitops:
    # -- Default gitops channel to install on remote clusters
    channel: "gitops-1.15"

global:
  # -- List of additional value files to be passed to the pattern
  extraValueFiles: []
  pattern: none
  # -- Repository URL pointing to the pattern
  repoURL: none
    # -- The branch or Git reference to use to deploy the pattern
  targetRevision: main
  options:
    applicationRetryLimit: 20
  secretStore:
    backend: "vault"

# -- Dictionary of all the clustergroups of the pattern
# @default -- depends on the individual settings
clusterGroup:
  # -- Dictionary of subscriptions for this specific clusterGroup
  subscriptions:
    # -- Name of the subscription
    acm:
      # -- The catalog source for this subscription
      source: redhat-operators
  # -- The set of cluters managed by ACM which is running inside this clusterGroup
  managedClusterGroups: {}
#    testRegion:
#      name: region-one
#      clusterPools:
#        testPool:
#          name: spoke
#          openshiftVersion: 4.10.18
#          baseDomain: blueprints.rhecoeng.com
#          platform:
#            aws:
#              region: ap-southeast-2
#          clusters:
#          - spoke1
#      labels:
#      - name: clusterGroup
#        value: region-one
#    testRegionTwo:
#      name: region-two
#      clusterDeployments:
#        myFirstCluster:
#          name: mcluster1
#          openshiftVersion: 4.10.18
#          baseDomain: blueprints.rhecoeng.com
#          platform:
#            azure:
#              baseDomainResourceGroupName: dojo-dns-zones
#              region: eastus
#      labels:
#        - name: clusterGroup
#          value: region-two

acm:
  # -- Just used for IIB testing, drives the source and channel for the MCE subscription triggered by ACM
  # @default -- Uses the official redhat sources
  mce_operator:
    source: redhat-operators
    channel: null
  # -- Used to control backup and restore of ACM
  # @default -- Backup operator is not enabled
  backup:
    # -- Enable the backup operator.
    # This will lead to OpenShift ADP operator being installed into the 
    # open-cluster-management-backup if AWS Security Token Service (STS) has not been enabled
    enabled: false
    # -- Custom OADP subscription specification (Optional)
    # @default -- Not configured and uses the correlated default OADP version linked to the ACM version
    oadpSubscriptionSpec:
    # -- Enables the managed service account component which allows auto-import
    # of managed clusters during restores
    enableAutomaticImport: false
    # -- Configures a backupschedule (Optional)
    # @default -- Create a schedule that runs every 2 hours with an expiration time of 120 hours
    schedule:
      # -- Cron schedule to perform backups
      veleroSchedule: "0 */2 * * *"
      # -- Expiration time for a scheduled backup resource (Optional)
      veleroTtl: 120h

# -- Default secretstore configuration variables
# @default -- depends on the individual settings
secretStore:
  # -- Name of the clustersecretstore to be used for secrets
  name: vault-backend
  kind: ClusterSecretStore
